[package]
name = "golduck"
version = "1.0.1"
edition = "2021"
description = "A cli tool to run and debug godot projects 🦆🌊"
license = "MIT"
repository = "https://github.com/wyvernbw/golduck"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive"] }
inquire = "0.6.0"
spinners = "4.1.0"
